In [47]:
import pandas as pd
import numpy as np
import nltk
import re
import seaborn as sns
import matplotlib.pyplot as plt
nltk.download('stopwords')
nltk.download('punkt')
df1 = pd.read_csv('/content/SMS_train (1) (1).csv',encoding='ISO-8859-1')
df2 = pd.read_csv('/content/SMS_test (2) (1).csv',encoding='ISO-8859-1')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [48]:
df = pd.concat([df1, df2], axis=0)
df

S. No.                                       Message_body     Label
0         1                         Rofl. Its true to its name  Non-Spam
1         2  The guy did some bitching but I acted like i'd...  Non-Spam
2         3  Pity, * was in mood for that. So...any other s...  Non-Spam
3         4               Will ü b going to esplanade fr home?  Non-Spam
4         5  This is the 2nd time we have tried 2 contact u...      Spam
..      ...                                                ...       ...
120     121  7 wonders in My WORLD 7th You 6th Ur style 5th...  Non-Spam
121     122  Try to do something dear. You read something f...  Non-Spam
122     123  Sun ah... Thk mayb can if dun have anythin on....  Non-Spam
123     124  SYMPTOMS when U are in love: "1.U like listeni...  Non-Spam
124     125  Great. Have a safe trip. Dont panic surrender ...  Non-Spam

[1082 rows x 3 columns]

In [49]:
df.reset_index(drop=True,inplace=True)
df

S. No.                                       Message_body     Label
0          1                         Rofl. Its true to its name  Non-Spam
1          2  The guy did some bitching but I acted like i'd...  Non-Spam
2          3  Pity, * was in mood for that. So...any other s...  Non-Spam
3          4               Will ü b going to esplanade fr home?  Non-Spam
4          5  This is the 2nd time we have tried 2 contact u...      Spam
...      ...                                                ...       ...
1077     121  7 wonders in My WORLD 7th You 6th Ur style 5th...  Non-Spam
1078     122  Try to do something dear. You read something f...  Non-Spam
1079     123  Sun ah... Thk mayb can if dun have anythin on....  Non-Spam
1080     124  SYMPTOMS when U are in love: "1.U like listeni...  Non-Spam
1081     125  Great. Have a safe trip. Dont panic surrender ...  Non-Spam

[1082 rows x 3 columns]

In [50]:
df.drop(['S. No.'],axis=1,inplace=True)

In [51]:
df.head()

Message_body     Label
0                         Rofl. Its true to its name  Non-Spam
1  The guy did some bitching but I acted like i'd...  Non-Spam
2  Pity, * was in mood for that. So...any other s...  Non-Spam
3               Will ü b going to esplanade fr home?  Non-Spam
4  This is the 2nd time we have tried 2 contact u...      Spam

In [52]:
df.isna().sum()

Message_body    0
Label           0
dtype: int64

In [53]:
df['Label'].value_counts()

Non-Spam    884
Spam        198
Name: Label, dtype: int64

In [54]:
df['Label']=df['Label'].map({'Spam':1,'Non-Spam':0})
df

Message_body  Label
0                            Rofl. Its true to its name      0
1     The guy did some bitching but I acted like i'd...      0
2     Pity, * was in mood for that. So...any other s...      0
3                  Will ü b going to esplanade fr home?      0
4     This is the 2nd time we have tried 2 contact u...      1
...                                                 ...    ...
1077  7 wonders in My WORLD 7th You 6th Ur style 5th...      0
1078  Try to do something dear. You read something f...      0
1079  Sun ah... Thk mayb can if dun have anythin on....      0
1080  SYMPTOMS when U are in love: "1.U like listeni...      0
1081  Great. Have a safe trip. Dont panic surrender ...      0

[1082 rows x 2 columns]

In [55]:
tweets = df['Message_body']
from nltk import TweetTokenizer
tk = TweetTokenizer()
tweets = tweets.apply(lambda x:tk.tokenize(x)).apply(lambda x:' '.join(x))
tweets

0                             Rofl . Its true to its name
1       The guy did some bitching but I acted like i'd...
2       Pity , * was in mood for that . So ... any oth...
3                   Will ü b going to esplanade fr home ?
4       This is the 2nd time we have tried 2 contact u...
                              ...                        
1077    7 wonders in My WORLD 7th You 6th Ur style 5th...
1078    Try to do something dear . You read something ...
1079    Sun ah ... Thk mayb can if dun have anythin on...
1080    SYMPTOMS when U are in love : " 1 . U like lis...
1081    Great . Have a safe trip . Dont panic surrende...
Name: Message_body, Length: 1082, dtype: object

In [56]:
tweets = tweets.str.replace('[^a-zA-Z0-9]+',' ')
tweets

<ipython-input-56-7bd7446417d3>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  tweets = tweets.str.replace('[^a-zA-Z0-9]+',' ')


0                               Rofl Its true to its name
1       The guy did some bitching but I acted like i d...
2       Pity was in mood for that So any other suggest...
3                      Will b going to esplanade fr home 
4       This is the 2nd time we have tried 2 contact u...
                              ...                        
1077    7 wonders in My WORLD 7th You 6th Ur style 5th...
1078    Try to do something dear You read something fo...
1079    Sun ah Thk mayb can if dun have anythin on Thk...
1080    SYMPTOMS when U are in love 1 U like listening...
1081     Great Have a safe trip Dont panic surrender all 
Name: Message_body, Length: 1082, dtype: object

In [57]:
from nltk.tokenize import word_tokenize
tweets = tweets.apply(lambda x: ' '.join([w for w in word_tokenize(x) if len(x)>=3]))
tweets

0                               Rofl Its true to its name
1       The guy did some bitching but I acted like i d...
2       Pity was in mood for that So any other suggest...
3                       Will b going to esplanade fr home
4       This is the 2nd time we have tried 2 contact u...
                              ...                        
1077    7 wonders in My WORLD 7th You 6th Ur style 5th...
1078    Try to do something dear You read something fo...
1079    Sun ah Thk mayb can if dun have anythin on Thk...
1080    SYMPTOMS when U are in love 1 U like listening...
1081      Great Have a safe trip Dont panic surrender all
Name: Message_body, Length: 1082, dtype: object

In [58]:
from nltk.stem import SnowballStemmer
ss = SnowballStemmer('english')
tweets = tweets.apply(lambda x:[ss.stem(i.lower()) for i in tk.tokenize(x)]).apply(lambda x:' '.join(x))
tweets

0                                 rofl it true to it name
1       the guy did some bitch but i act like i d be i...
2          piti was in mood for that so ani other suggest
3                           will b go to esplanad fr home
4       this is the 2nd time we have tri 2 contact u u...
                              ...                        
1077    7 wonder in my world 7th you 6th ur style 5th ...
1078       tri to do someth dear you read someth for exam
1079    sun ah thk mayb can if dun have anythin on thk...
1080    symptom when u are in love 1 u like listen son...
1081        great have a safe trip dont panic surrend all
Name: Message_body, Length: 1082, dtype: object

In [59]:
from nltk.corpus import stopwords
sw = stopwords.words('english')
tweets = tweets.apply(lambda x: [i for i in word_tokenize(x) if i not in sw]).apply(lambda x: ' '.join(x))
tweets

0                                          rofl true name
1       guy bitch act like interest buy someth els nex...
2                                   piti mood ani suggest
3                                   b go esplanad fr home
4       2nd time tri 2 contact u u 750 pound prize 2 c...
                              ...                        
1077    7 wonder world 7th 6th ur style 5th ur smile 4...
1078                     tri someth dear read someth exam
1079    sun ah thk mayb dun anythin thk book e lesson ...
1080    symptom u love 1 u like listen song 2 u get st...
1081                   great safe trip dont panic surrend
Name: Message_body, Length: 1082, dtype: object

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
data = vec.fit_transform(tweets)
data

<1082x2996 sparse matrix of type '<class 'numpy.float64'>'
	with 9614 stored elements in Compressed Sparse Row format>

In [61]:
print(data)

  (0, 1849)	0.5086856793431559
  (0, 2727)	0.5352804139572925
  (0, 2257)	0.6743246681420617
  (1, 1189)	0.19084717659108363
  (1, 2787)	0.2620897628588603
  (1, 1234)	0.3166286972359124
  (1, 2872)	0.22002695063463382
  (1, 1878)	0.25587622919424974
  (1, 1034)	0.29329608266677626
  (1, 2448)	0.26551480891862445
  (1, 677)	0.26551480891862445
  (1, 1475)	0.307577621142851
  (1, 1623)	0.20980773882403927
  (1, 396)	0.3419878575694143
  (1, 607)	0.36211655551990307
  (1, 1307)	0.2588858462402129
  (2, 2548)	0.5165656915002457
  (2, 463)	0.36716239650585775
  (2, 1802)	0.5469696796701571
  (2, 2038)	0.5469696796701571
  (3, 1384)	0.3883344606933877
  (3, 1185)	0.630740525885995
  (3, 1062)	0.5956800313099777
  (3, 1263)	0.3106896135077221
  (4, 2170)	0.24144740187001762
  :	:
  (1079, 1819)	0.2633677871797729
  (1079, 2553)	0.2544650331411059
  (1079, 1611)	0.2410408066920934
  (1079, 628)	0.23101411970886698
  (1079, 2647)	0.4820816133841868
  (1079, 1734)	0.21063371947658105
  (1079, 1

In [62]:
data.shape

(1082, 2996)

In [63]:
y = df['Label'].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,y,test_size=0.30,random_state=42)

In [65]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [66]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y_pred)
score

0.8338461538461538

In [67]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=5)
bayes=BernoulliNB()
model=SVC()
forest=RandomForestClassifier()
tree=DecisionTreeClassifier()
lst=[knn,bayes,model,forest,tree]

In [70]:
for i in lst:
  print('Model is',i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  y_pred
  print(y_pred)
  print("CM is")
  print(confusion_matrix(y_test,y_pred))
  print("Accurcay score is",accuracy_score(y_test,y_pred))
  print("Classification report is")
  print(classification_report(y_test,y_pred))
  print('*'*100)

Model is KNeighborsClassifier()
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
CM is
[[269   0]
 [ 52   4]]
Accurcay score is 0.84
Classification report is
              precision    recall  f1-score   support

           0       0.84      1.00      0.91       269
           1       1.00      0.07      0.13        56

    accuracy                           0.84       325
   macro avg 